export default {
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  NO_ACCESS_TOKEN_PROVIDED: "NO_ACCESS_TOKEN_PROVIDED",
  NOT_FOUND: "NOT_FOUND",

  UNAUTHORIZED: "UNAUTHORIZED",
  USER_ALREADY_EXIST: "USER_ALREADY_EXIST",

  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
} as const;
